export const CardData = [
  "Oferece uma tostinha com queijo a alguém do teu círculo.",
  "Se ofereceres a alguém que não conheces, dirige-te à frente da capela e diz “Esta foi para ti, meu rico São Miguel”.",
  "Pergunta às pessoas com quem estiveres a falar se querem que vás buscar bebida. E se estão confortáveis.",
  "Comenta o bom momento do Benfica, mas diz que no futebol tudo é possível e que não vale a pena embandeirar em arco.",
  "A expressão “embandeirar em arco” é imprescindível.",
  "Vai ver o moinho sozinho.",
  "Se alguém te perguntar o que foste fazer, diz que foste ver o moinho sozinho. O importante é dares destaque a esta pequena rima: “Moinho sozinho”.",
  "Não deixes de referir que Super Bock é melhor do Sagres.",
  "Vai ver o Castelo com alguém.",
  "Vai ver a Serra com alguém. Diz que gostavas de ter uma casa lá em cima e desenvolve a conversa a partir daí.",
  "Finge que tens uma pequena comichão nas costas e pede a alguém que te ajude a coçar. Dá algumas indicações até a pessoa perceber onde está a tua comichão. Diz-lhe que achas graça à palavra “Comichão”",
  "e agradece a ajuda.",
  "Pergunta a alguém desconhecido se tem um lenço emprestado. Se tiver, faz com que cheguem à conclusão que os lenços não se emprestam",
  "e sorriam os dois.",
  "Tenta acertar nas horas e nos minutos. Se acertares, partilha com alguém a tua pontaria. Se falhares, exagera um bocado nas lamentações e diz que dantes acertavas muitas vezes, mesmo que seja mentira.",
  "Tenta adivinhar a temperatura. Se acertares em cheio, pede que alguém te abrace e te dê os parabéns.",
  "Pergunta à pessoa que está ao teu lado se ela acha que devias vestir um casaco.",
  "Na pista de dança, faz um passo de ballet muito discretamente.",
  "Quando estiveres a dançar, inventa um passo que envolva o pé coxinho.",
];
