export const CardData = [
  "Oferece uma tostinha com queijo a alguém do teu círculo.",
  "Se ofereceres a alguém que não conheces, dirige-te à frente da capela e diz “Esta foi para ti, meu rico São Miguel”.",
  "Pergunta às pessoas com quem estiveres a falar se querem que vás buscar bebida. E se estão confortáveis.",
  "Comenta o bom momento do Benfica, mas diz que no futebol tudo é possível e que não vale a pena embandeirar em arco.",
  "A expressão “embandeirar em arco” é imprescindível.",
  "Vai ver o moinho sozinho.",
  "Se alguém te perguntar o que foste fazer, diz que foste ver o moinho sozinho. O importante é dares destaque a esta pequena rima: “Moinho sozinho”.",
  "Não deixes de referir que Super Bock é melhor do Sagres.",
  "Vai ver o Castelo com alguém.",
  "Vai ver a Serra com alguém. Diz que gostavas de ter uma casa lá em cima e desenvolve a conversa a partir daí.",
  "Finge que tens uma pequena comichão nas costas e pede a alguém que te ajude a coçar. Dá algumas indicações até a pessoa perceber onde está a tua comichão. Diz-lhe que achas graça à palavra “Comichão”",
  "e agradece a ajuda.",
  "Pergunta a alguém desconhecido se tem um lenço emprestado. Se tiver, faz com que cheguem à conclusão que os lenços não se emprestam",
  "e sorriam os dois.",
  "Tenta acertar nas horas e nos minutos. Se acertares, partilha com alguém a tua pontaria. Se falhares, exagera um bocado nas lamentações e diz que dantes acertavas muitas vezes, mesmo que seja mentira.",
  "Tenta adivinhar a temperatura. Se acertares em cheio, pede que alguém te abrace e te dê os parabéns.",
  "Pergunta à pessoa que está ao teu lado se ela acha que devias vestir um casaco.",
  "Na pista de dança, faz um passo de ballet muito discretamente.",
  "Quando estiveres a dançar, inventa um passo que envolva o pé coxinho.",
  "Diz ao DJ que curtes bue da cena dele e manda-lhe um beijinho com as duas mãos.",
  "Olha fixamente para alguém até a pessoa te pedir para parar.",
  "Em conversa, usa a palavra “astrolábio” pelo menos uma vez.",
  "Se conseguires usar mais do que uma vez, perfeito.",
  "Dá a entender a alguém que preferes o arroz de pato mais soltinho.",
  "Chega perto do DJ e pergunta-lhe se está a pensar meter",
  "a Asereje.",
  "Se estiveres a beber cerveja, revela uma regra tua à primeira pessoa que encontrares: por cada três cervejas, bebes sempre um copo de água. No fim pisca-lhe o olho e pede segredo.",
  "Para a pessoa que está ao teu lado, defende que vem aí uma enorme crise financeira em 2024 e que a melhor solução é beber até cair. Pergunta-lhe se vai num whisky com duas pedras de gelo.",
  "Encontra maneira de tocar com a mão nas costas de alguém que não conheças. Se ela der a entender que ficou desconfortável, pede desculpa com uma mão na zona do tricep.",
  "Cita uma frase de Gandhi até ao final da Festa. Podes usar esta: “Seja a mudança que você quer ver no mundo”. Se não gostares, procura alternativa no Google.",
  "Arranja maneira de alguém fazer um passo de tango.",
  "Em conversa, elabora uma pequena teoria sobre a Guerra na Ucrânia.",
  "Finge uma chamada de telemóvel e gesticula como se te estivessem a pedir para ir embora. Desabafa com a primeira pessoa que encontrares que não vais obedecer que não há ninguém que tenha mão em ti. E que sempre foste assim desde que te conheces.",
  "Tenta iniciar uma onda como num estádio de futebol. Se não tiveres confiante, troca de papel.",
  "Elogia o espaço da festa, mas diz que se tivesse sido tu a organizar, tinhas comprado um escorrega e contratado a Banda Recreativa Portomosense.",
  "Diz à pessoa que acabou de passar por ti que deixou cair qualquer coisa.",
  "Comenta uma das músicas da seguinte forma: “Ganda malha.”. Se alguém tiver ouvido, pergunta: “Não é alta malha?”",
  "Faz de propósito e fala mais baixo do que o habitual. Só ganhas se a pessoa te pedir para repetires. Se não pedir, tens de beber qualquer coisa de penalty, nem que seja um copo de água.",
  "Queixa-te que estamos no princípio do mês e já tens poucos dados móveis.",
  "Inventa uma história qualquer que te aconteceu ontem. Tem de envolver as palavras “carro”, “guarda-chuva”, “isqueiro” e “manteiga”.",
  "Pergunta a alguém se quer jogar ao jogo do sério.",
  "Assobia até alguém reparar.",
  "Entra e sai da festa e diz a alguém que se está melhor cá fora. Se a pessoa aceder, ajuda-a a sair para a rua, mesmo sendo óbvio que ela não precisa e que tem autonomia.",
  "Usa a expressão “Dar no álcool”.",
  "Diz a alguém que precisas de ir ao carro. Mesmo que não precises. Mesmo que nem tenhas carro. Mesmo que a pessoa saiba disso perfeitamente.",
  "Relembra as pessoas do Corcunda de Notre-Dame. Diz que o filme te marcou de algum modo que ainda não tens bem definido dentro de ti.",
  "Se a conversa se alongar, diz que adoras o nome Quasimodo.",
  "Fala sobre o problema de mão-de-obra para a apanha da fruta e que é inconcebível que a fruta tenha acabado no chão. Demonstra preocupação com o facto de a comida da Festa poder sobrar.",
  "Usa a expressão “Dar no álcool”.",
  "Usa a expressão “Dar no álcool”.",
  "Repete “Olá, estás bem?” cinco vezes à mesma pessoa.",
  "Diz a alguém que sentes ansiedade perante desconhecidos, mas que encontraste o truque certo: pensar numa multidão como um monstro sem cabeça. Revela que este pensamento é do Charlie Chaplin e pisca o olho à pessoa.",
  "Toma atenção ao volume da",
  "música. Se achares que está muito alto, aproxima-te do Rafa, do Chico ou do Pedro e diz-lhes “Não achas que a música está muito alta?”.",
  "Repete “Olá, estás bem?” cinco vezes à mesma pessoa.",
  "Em conversa, faz um reparo em relação ao local do evento e diz, seja de forma autêntica ou não, que achas errado fazer-se uma festa tão perto de uma capela. Usa a palavra “heresia” e dá a entender que se fosse contigo, escolhias outro sítio.",
  "Diz a alguém com que não costumes falar que tens muitas saudades de andar de trotinete.",
  "Diz que te vais lançar por conta própria com um negócio de pizzas triangulares e que achas que tem faltado um ingrediente essencial em todas pizzas que comeste até hoje: Nestum.",
  "Tenta descobrir quanto é que está o resultado entre o Rafa e o Pedro no ténis de mesa. Quando descobrires, diz ao Pedro que sentes imenso por ele e para ele não desistir de tentar.",
  "Discretamente, diz a alguém que estás viciado em raspadinhas. Diz que te tens tentado controlar mas que precisas de ajuda de fora. Podes puxar a pessoa pela manga da camisola para transmitir mais urgência.",
  "Pergunta a alguém onde é a casa de banho, mesmo que depois seja óbvio que não precisas de ir. Diz que só te sentes seguro quando sabes onde é a casa de banho.",
  "Pergunta a alguém se tem isqueiro, mesmo que não precises.",
  "Diz que só querias saber.",
  "Organiza uma pequena votação sobre o melhor gelado da Epá. Faz lobby pelo Minimilk.",
  "Aproxima-te de alguém e diz-lhe “Droga” em segredo, nada mais.",
  "Aproxima-te de alguém e diz-lhe “Droga” em segredo, nada mais.",
  "Aproxima-te de alguém e diz-lhe “Droga” em segredo, nada mais.",
  "Chama alguém que esteja longe de ti, pede-lhe que se aproxime e diz que só a querias abraçar.",
  "Chama alguém que esteja longe de ti, pede-lhe que se aproxime e diz que só a querias abraçar.",
  "Chama alguém que esteja longe de ti, pede-lhe que se aproxime e diz que só a querias abraçar.",
  "Chama alguém que esteja longe de ti, pede-lhe que se aproxime e diz que só a querias abraçar.",
  "Numa conversa sobre as tuas",
  "relações, diz que tens vindo a afastar do teu círculo de amizade todas as pessoas que não fazem a cama. Deixa no ar que para ti é uma red flag.",
  "Começa a falar sobre lavar a loiça e diz que deixaste de acreditar em determinada marca de detergente porque um dia te deixou ficar mal num almoço de família.",
  "Incentiva alguém a beber uma quantidade maior usando a expressão: “Manda-lhe uma trombada”.",
  "Incentiva alguém a beber uma quantidade maior usando a expressão: “Manda-lhe uma trombada”.",
  "Em conversa sobre dinheiro, diz que vais investir as tuas poupanças em obrigações do tesouro francês e para não se atreverem a questionar o teu investimento.",
  "Numa conversa sobre trabalho, diz que o problema disto foi as pessoas terem deixado de picar o ponto.",
  "Numa conversa sobre trabalho, diz que o problema disto foi as pessoas terem deixado de picar o ponto.",
  "Numa conversa sobre trabalho, diz que o problema disto foi as pessoas terem deixado de picar o ponto.",
  "Abraça alguém de uma forma diferente. Pode ser na cintura.",
  "Abraça alguém de uma forma diferente. Pode ser na cintura.",
  "Pergunta a alguém com quem tenhas confiança se a podes pegar ao colo durante alguns segundos.",
  "Pergunta a alguém com quem tenhas confiança se a podes pegar ao colo durante alguns segundos.",
  "Pergunta a alguém com quem tenhas confiança se a podes pegar ao colo durante alguns segundos.",
  "Diz que te apetece aprender uma nova língua. Uma língua que aparentemente não te vá dar grande vantagem profissional, o importante é que alguém pergunte porque o queres fazer. Quando fizerem a pergunta, diz que não sabes a razão e ri-te.",
  "Disserta, sem rodeios, sobre rações para animais.",
  "Se for preciso mente, mas diz que já experimentaste aqueles enlatados para gatos.",
  "Cumprimenta um grupo de pessoas com “Alô maltaaaaa, tudo nice?”. Se for estranho, pede desculpa e afasta-te um bocadinho. Depois volta e diz que estavas a representar.",
  "Inventa um novo cumprimento, uma espécie de alternativa ao aperto de mão masculino. Partilha-o com o maior número de pessoas da festa.",
  "Leva alguém a imaginar o que seria o Marcelo Rebelo de Sousa estar presente na Festa.",
  "Se estiveres à vontade para isso, faz uma pequena imitação do que seria o comportamento do Professor neste contexto.",
  "Convida alguém para ir ver a cozinha. Quando lá estiverem, olha em volta e diz, “Boa cozinha, nem dei pela falta de uma Bimby”.",
  "Pergunta à pessoa da festa que te é mais próxima se quer ir fumar uma djadja.",
  "Pergunta à pessoa da festa que te é mais próxima se quer ir fumar uma djadja.",
  "Pergunta à pessoa da festa que te é mais próxima se quer ir fumar uma djadja.",
  "Se alguém te vir a tirar uma peça de roupa porque estás com calor, diz-lhe “Agora é que esta pista me vai conhecer”. Se a pessoa ficar pensativa, diz-lhe que está tudo bem e que a amas do fundo do coração.",
  "Pede o microfone e diz que o pessoal é jovem e a malta curte.",
  "Pede o microfone e diz que o pessoal é jovem e a malta curte.",
  "Diz que tens saudades de ouvir Nicolas Jaar. Exagera neste sentimento e se conseguires finge um princípio de choro.",
  "Diz ao DJ para dedicar uma música ao São Miguel.",
  "Diz que tens saudades de tocar flauta.",
  "Pergunta a alguém se viu Game of Thrones. Se a pessoa tiver visto e consentir, pergunta se não é ganda série e termina a conversa de forma fria e enigmática.",
  "Se disser que não viu, chateia-a um bocado até ela revelar desconforto.",
  "Perde algum tempo a comentar a qualidade da infraestrutura e pede uma opinião a um desconhecido sobre, por exemplo, o tempo que demorou a construir, os materiais utilizados e o potencial de expansão.",
  "Diz a alguém que gostavas de ir a Fátima a pé. Se a pessoa perguntar porquê, diz que andas a sentir.",
  "Pergunta a alguém se acha que ainda vai haver o Festival Alive em 2040. Se a pessoa disser que não, defende que o Alive nunca vai acabar e podes dizer uma asneira como sinal de revolta.",
  "Tira uma selfie e faz bico de pato. Se alguém achar estranho pede respeito pela tua personalidade.",
  "Defende que o importante numa pessoa é o interior.",
  "Defende que o importante numa pessoa é o interior.",
  "Defende que o importante numa pessoa é o interior.",
  "Enumera algumas das coisas que queres para o Natal. Entre as coisas materiais que possam ser tidas por normais (podes inventar), diz que este ano ficarias satisfeito se recebesses amor. Se a pessoa não aderir, diz que achas que é realmente o mais importante do Natal.",
  "Combina com alguém que te seja próximo. Perante uma terceira pessoa, um de vocês diz a palavra combinada e o outro inventa um tique. Um tique por cada vez que se disser essa palavra. Até serem descobertos.",
  "Aparece ao pé dos teus amigos a comer de boca aberta. Até que um deles se revele mais sensível a regras de etiqueta e te peça para ter modos.",
  "Um pouco afastado da pista, confidencia a alguém que ainda hás-de ir a um programa de talentos e revela confiança no primeiro minuto de dança. Ao ponto de a pessoa acreditar que estás a falar a sério.",
  "Se tiveres com confiança, entra na pista a fazer exercícios de aquecimento.",
  "Diz que tens saudades",
  "de tocar flauta.",
  "Mais ou menos duas ou três horas depois, volta a repetir à mesma pessoa que tens saudades de tocar flauta.",
  "Revela a alguém que sempre tiveste um carinho especial por gafanhotos.",
  "Entre a macaca e o jogo do elástico, tens de dizer que a macaca é muito mais divertida. É uma discussão que tens de ganhar esta noite. A única.",
  "Fala sobre a influência da Lua",
  "sobre o teu signo. Se a pessoa não acreditar nesta influência, jura pela tua vida que sentes um arrepio na espinha quando está lua cheia.",
  "Finge que metes alguma substância no copo de alguém que conheças. Se a pessoa se mostrar perturbada, diz para ela não se preocupar, que é só um bocadinho de ecstasy.",
  "Revela a alguém que sempre tiveste um carinho especial por gafanhotos.",
  "Diz que vais à casa de banho lavar os dentes. Se alguém questionar tanta higiene, diz que queres entrar em 2024 com um sorriso Colgate e que para teres bons resultados, é preciso começar com antecedência. Dá um sermão sobre o fazer as coisas com antecedência até a pessoa não te conseguir ouvir mais.",
  "Finge que metes alguma substância no copo de alguém que conheças. Se a pessoa se mostrar perturbada, diz para ela não se preocupar, que é só um bocadinho de ecstasy.",
  "Desafia alguém para o pedra",
  "papel tesoura. O que está em jogo: decidir qual de vocês é que vai buscar bebida.",
  "Arranja um pretexto qualquer para fazeres um pequeno passo de uma dança tradicional à tua escolha.",
  "Finge que metes alguma substância no copo de alguém que conheças. Se a pessoa se mostrar perturbada, diz para ela não se preocupar, que é só um bocadinho de ecstasy.",
  "Convida alguém para dançar. Se a pessoa recusar, tenta fazer o moonwalk no sentido da pista. Se é para ser rejeitado, que se saia de cena com estilo.",
  "Cheira o pescoço de alguém. Se tiver perfume, tenta adivinhar qual é e no fim pergunta se acertaste.",
  "Mesmo que a conversa não seja esta, interrompe dizendo que o Bem triunfará sobre o Mal. Se quiseres ser muito teatral, estás à vontade.",
  "Diz a alguém que hoje é até cair, numa alusão à quantidade de álcool que pretendes ingerir. Se a pessoa ficar surpreendida, pede-lhe para ter calma nessa hora.",
  "Chama alguém à parte, diz-lhe que tens estado a apreciar o seu comportamento na festa. Podes deixar só isto no ar e ir embora.",
  "Interrompe uma conversa séria entre duas pessoas e pergunta se algum deles tem shakes da Vodafone.",
  "Interrompe uma conversa séria entre duas pessoas e pergunta se algum deles tem shakes da Vodafone.",
  "Apoia-te no ombro de alguém, mesmo que não tenhas assim tanta confiança com essa pessoa.",
  "Dá a entender que o Pokemon Go foi uma moda que toda a gente pensa ter acabado, mas que foste uma das pessoas que manteve essa sede de capturar pokemons. Diz a alguém, discretamente, que tens a sensação de que podes apanhar o Pikachu nas imediações do moinho. Pede para essa pessoa te acompanhar.",
  "Lembra-te das Navegantes da Lua, fala com alguém sobre isso e dá um tom nostálgico a essa conversa.",
  "Responde a alguém “Quem diz é quem é”.",
  "Responde a alguém “Quem diz é quem é”.",
  "Usa a expressão “Xau Laura” pelo menos três vezes durante a Festa.",
  "Usa a expressão “Xau Laura” pelo menos três vezes durante a Festa.",
  "Usa a expressão “Xau Laura” pelo menos três vezes durante a Festa.",
  "Leva alguém para a pista às cavalitas.",
  "Diz a uma pessoa à tua escolha que estás muito indeciso(a) em relação ao que te apetece comer, portanto a tua solução será fazer um-dó-li-tá em frente à mesa da comida. Deixa que a pessoa perceba que este é o teu método de desempate e pense que tu estás a ficar chalupa.",
  "Diz ao Rafa que ele tem buéda estilo.",
  "Diz ao Rafa que ele tem buéda estilo.",
  "Diz ao Rafa que ele tem buéda estilo.",
  "Pergunta a alguém se acha que tem estilo.",
  "Lança a discussão “Entre os doces conventuais, que doce serias?”. Quem disser que era um Tachinho de Dom Abade deve ser presenteado com uma cerveja ou outra bebida à sua escolha.",
  "Se os teus amigos(as) te conhecerem bem e não fores um utilizador(a) regular desta expressão, surpreende-os com um sonoro “Graças a Deus.”",
  "Assegura perante alguém que contigo não fazem farinha.",
  "Assegura perante alguém que contigo não fazem farinha.",
  "Recorda que “Pão pão, queijo queijo.”",
  "Recorda que “Pão pão, queijo queijo.”",
  "Finge que estás com dificuldade em dizer uma palavra até alguém dizer a palavra como deve ser. Encara essa pessoa como uma grande amiga e agradece-lhe com um abraço demorado, ao ponto de ela achar que está a demorar tempo demais.",
  "Demonstra algum tipo de preocupação. Se fores fumador, chega ao ponto de dizer à pessoa que está ao teu lado que precisas de um cigarro. Se não fores, diz que hoje precisas mesmo de um cigarro para desanuviar e pergunta se essa pessoa",
  "te acompanha lá fora.",
  "Assegura perante os teus amigos e amigas que ainda vais tirar um curso de informática.",
  "Se eles questionarem a pertinência, diz que as novas tecnologias são o futuro.",
  "Trata a pessoa ao teu lado como se fosse um animal de estimação. Dá-lhe festas no cabelo, abraça-a carinhosamente e no final, se ela estiver a consentir demasiado, pede-lhe para dar a patinha.",
  "Se vires que alguém quer alguma coisa, antecipa-te e oferece-lhe o que ela pretende. Se a pessoa não te conhecer, faz o símbolo do coração com as duas mãos.",
  "Se te conhecer, diz-lhe que sentiste uma espécie de chamamento.",
  "Diz ao teu grupo ou à pessoa com quem estejas a falar que foste fazer análises ao sangue, detectaram Noite e estás um bocado preocupado(a).",
  "Antecipa tendências para o próximo verão. Começa pela cor, passa por uma peça de roupa e discute um acessório. Se não concordarem contigo, diz que noutro dia estiveste com um estilista famosíssimo, mas que não queres dizer o nome porque te foi pedido que guardasses segredo.",
  "Dá a entender que o Pokemon Go foi uma moda que toda a gente pensa ter acabado, mas que foste uma das pessoas que manteve essa sede de capturar pokemons. Diz a alguém, discretamente, que tens a sensação de que podes apanhar o Pikachu nas imediações do moinho. Pede para essa pessoa te acompanhar.",
  "Dá a entender que tu, com a ajuda de um drone, seriam uma excelente dupla no combate aos incêndios.",
  "Permite-te começar a usar a expressão “Pertence”. Quando algo é suposto acontecer, dizes “Pertence”. Ensaia aqui. Beber um copo de água para evitar a ressaca: Pertence. Treina a expressão com os teus amigos e amigas.",
  "Mesmo que toda a gente saiba, não deixes de recordar que Mentos, misturado com Coca-Cola é uma combinação explosiva.",
  "Pergunta ao Rafa, ao Chico ou ao Pedro se não têm vergonha de não ter dito ao pessoal para que o tema fosse Halloween. Diz que a ideia do Escorpião é uma merda e que nos odeias.",
  "Permite-te começar a usar a expressão “Pertence”. Quando algo é suposto acontecer, dizes “Pertence”. Ensaia aqui. Beber um copo de água para evitar a ressaca: Pertence. Treina a expressão com os teus amigos e amigas.",
  "Exagera na quantidade de álcool que já bebeste.",
  "Diz, por exemplo, que já vais na vigésima imperial mesmo que seja óbvio que é mentira.",
  "Tinha de haver esta, não é? Beijinho na boca.",
  "Anima a pista de dança com a frase “O pessoal é jovem e a malta curte.” Repete-a até ninguém se esquecer que essa é a tua filosofia.",
  "Junta 5 pessoas para dançar. Se conseguires, és grande.",
  "Junta 5 pessoas para dançar. Se conseguires, és grande.",
  "Avalia a qualidade do som",
  "de 0 a 10. Se estiver acima de 7, transmite essa avaliação ao DJ. Se estiver abaixo de 7, passa pelo DJ e faz-lhe um sinal esquisito.",
  "Está céu limpo. Tenta saber o nome de todas as constelações que se vêem a partir daqui. Se não souberes, inventa nomes e partilha com alguém como se falasses com conhecimento de causa e as constelações fossem a tua praia.",
  "Diz que viste um morcego. Diz que tens medo e que nunca achaste piada nenhuma ao Batman.",
  "Num grupo, finge que contaste alguma coisa embaraçosa sobre uma das pessoas presentes e riam-se para ela quando começar a reagir.",
  "Diz que te tens entretido",
  "a fazer vasos em barro nos teus tempos livres.",
  "Pergunta a alguém se tem os pés quentes. Se a pessoa tiver, diz que só querias saber se ela tinha os pés quentes. Se não tiver, abraça-a sem dizeres mais nenhuma palavra.",
  "Pergunta se há “brancúlia”.",
  "Pergunta se há “brancúlia”.",
  "Pergunta se há “brancúlia”.",
  "Recorda um passado de alcoolismo, mesmo que seja mentira e isso seja óbvio para quem te está a ouvir.",
  "Oferece-te para tirar uma fotografia a alguém.",
  "Sê profissional, fala da luz, da pose e da expressão. No fim, perde algum tempo com a pessoa a editar e se chegarem a um ponto de entendimento, abracem-se.",
  "Tira uma fotografia em grupo, publica-a no Instagram e inaugura um hashtag: #festadoescorpião.",
  "Cumprimenta alguém com quatro beijinhos na cara. Podes dar um quinto, na testa.",
  "Pede à pessoa com quem estás a falar que fale mais alto.Depois pede para falar mais baixo até que ela fique com a sensação de que a estás a tratar como se fosse uma coluna Bluetooth. Porque as pessoas não têm fios LOL.",
  "Cumprimenta a primeira pessoa que passar por ti em romeno. “Olá” é “Buna ziua”. Se a pessoa estranhar, diz que é “Olá” em romeno.",
  "Pede à pessoa com quem estás a falar que fale mais alto.Depois pede para falar mais baixo até que ela fique com a sensação de que a estás a tratar como se fosse uma coluna Bluetooth. Porque as pessoas não têm fios LOL.",
  "Na pista, dança num estilo completamente contrário ao da música durante um minuto. Se alguém te disser que não se dança assim naquele espaço de tempo, ganhaste. Pede uma gratificação a essa pessoa.",
  "Tenta saber como está a festa ao nível de signos. Investiga as compatibilidades entre eles e discorre sobre o assunto.",
  "Tira uma fotografia em grupo, publica-a no Instagram e inaugura um hashtag: #festadoescorpião.",
  "Diz a uma pessoa que sabes fazer um bom arroz de tamboril. Podes continuar e dizer que estás empenhado em ser melhor na cozinha.",
  "Arranja maneira de, numa conversa ou discussão, teres oportunidade de dizer que mais vale um pássaro na mão do que dois a voar.",
  "Cuidado com esta carta. Pergunta se alguém quer ir beber um shot de whisky. Se a pessoa disser que “não”, pede-lhe calma e diz que estavas a brincar. Se disser que sim, têm de ir beber um shot de whisky.",
  "Diz a alguém que precisas de ir apanhar ar. Leva essa pessoa a inspirar fundo e diz que este ar é bom para limpar os pulmões.",
  "Pergunta a alguém se acha que vai haver karaoke. Diz que querias cantar a “Toxic” da Britney Spears e que tens o recorde nacional dessa música no Singstar.",
  "Diz que a Noite é a tua Pátria e que só a Ela deves obediência.",
  "Diz que a Noite é a tua Pátria e que só a Ela deves obediência.",
  "Diz que a Noite é a tua Pátria e que só a Ela deves obediência.",
  "Sugere que a festa teria sido muito melhor se pudesses ter vindo vestido(a) de zebra.",
  "Tenta saber onde é o moinho do Alqueidão da Serra. Procura vê-lo com alguém e aponta para lá a dizer “O moinho do Alqueidão é ali, estás a ver?” Não desistas até a pessoa o ver e celebrem quando esse momento chegar.",
  "Pergunta a alguém se acha que devias meter um piercing. Se já tiveres, pede opinião sobre um novo piercing para 2024.",
  "Numa conversa, finge que percebes alguma coisa sobre a história do Castelo de Porto de Mós. Se perceberes, escolhe outra carta.",
  "Insurge-te contra um programa de televisão à tua escolha.",
  "Bate umas palminhas para aquecer as mãos e diz que não há nada melhor para aquecer. Se houver encadeamento, bate com os pés no chão e diz que a lógica é a mesma até a outra pessoa pensar “Que cena, esta pessoa sabe mesmo aquecer-se sozinha.”",
  "Pergunta a alguém se sabe trocar um pneu. Se disser que sim, mostra o teu agrado e dá a entender que é das coisas que mais admiras numa pessoa.",
  "Recomenda a alguém o uso de um gestor de passwords. Diz que é mais fácil e mais seguro e promete que só queres o melhor para essa pessoa. Se preferires, diz-lhe esta última parte ao ouvido.",
  "Finge que estás a fazer um story. Vira a câmara para vocês, mostra que não estavas a filmar e diz que só te apeteceu curtir um bocadinho.",
  "Fala com alguém imitando a voz da Clara de Sousa.",
  "Pede a alguém para te imaginar vestido(a) de esquimó.",
  "Finge que estás a fazer um story. Vira a câmara para vocês, mostra que não estavas a filmar e diz que só te apeteceu curtir um bocadinho.",
  "Vai ao pé da fogueira e pergunta se alguém sabe como é que foi acesa. Se não te responderem, diz que tinha sido uma boa oportunidade de mostrares uma nova técnica que envolvia uma lata de Ajax e um pau de incenso.",
  "Pede a concentração de alguém para responder a uma adivinha difícil. Pergunta-lhe:",
  "“Qual é coisa qual é ela que Rátátá rátátá?”",
  "Diz que não consegues dormir se não tiveres quatro iogurtes de manga no frigorífico. E sementes de chia na despensa.",
  "Pergunta ao aniversariante se o brinde pode ser com Champomy.",
  "Lança um debate sobre canalização.",
  "Lança um debate sobre canalização.",
  "Diz que pensas ter um filho chamado Alfredo.",
  "Confidencia que tens dormido com uma luz de presença",
  "e que tens dormido muito melhor ultimamente.",
  "Diz a alguém que uma boa Água das Pedras dá 20-0 a qualquer água com sabores.",
  "Convence alguém a comer uma maçã.",
  "Não desistas facilmente.",
  "Pergunta a alguém se gosta mais de cães ou de gatos e transforma a resposta numa conversa séria. No fim, mostra-lhe este papel.",
  "Pergunta a alguém se gosta de figos secos. Se não gostar, diz qualquer coisa para a convencer a fazer as pazes com este fruto. Diz, por exemplo, que um determinado famoso adora figos secos. Pode ser o José Mourinho ou a Luana do Bem.",
  "Confidencia a alguém que o que mais gostas neste tipo de festas é o amor que se sente no ar.",
  "Propõe a uma das pessoas que esteja na fogueira que joguem à sardinha.",
  "Tem uma conversa mais quente com alguém. No bom sentido da palavra “quente” kkkkkkkkkkkkk, malandrice.",
  "Confidencia a alguém que o que mais gostas neste tipo de festas é o amor que se sente no ar.",
  "Confidencia a alguém que o que mais gostas neste tipo de festas é o amor que se sente no ar.",
  "Vai para a pista de óculos de sol. Se não tiveres, pede a alguém que te empreste.",
  "Sustenta a tese de que o Carnaval funcionou como uma espécie de cavalo de tróia do Halloween.",
  "Sustenta a tese de que o Carnaval funcionou como uma espécie de cavalo de tróia do Halloween.",
  "Anuncia que o teu novo hobbie são bonsais.",
  "Diz que o que mais te tem surpreendido éconseguires controlar a direcção dos troncos com recurso a arame.",
  "Lança uma questão sobre um problema de primeiro mundo. Sobre as marcas de água engarrafada, por exemplo.",
  "Diz a alguém que está sujo com comida e oferece-te para limpar. Se a pessoa perceber que estás a gozar, diz-lhe que a ela ninguém lhe passa a perna e dá-lhe um beijinho por isso.",
  "Pergunta a alguém se já comeu leitão em tronco nu.",
  "Fala durante algum tempo com a voz do Bruno Aleixo.",
  "Defende que a toxicodependência é um projecto de vida completamente legítimo.",
  "Simula uma dificuldade na fala até alguém te perguntar se estás bem.",
  "Chama o Chico à parte e diz-lhe que ele está despenteado. Só podes voltar à festa com ele quando ele estiver recomposto.",
  "Diz ao Pedro que ele não percebe um chavelho de ténis de mesa. Como isto é um tema sensível para ele, tem algum cuidado na maneira como o dizes. O ideal é que lho digas ao ouvido.",
  "Comenta a personalidade de alguém dizendo que essa pessoa “É de luas.”",
  "Dá os parabéns mais do que uma vez ao aniversariante.",
  "Se ele começar a estranhar, diz-lhe que é um prazer para ti estar diante de um Rei.",
  "Segreda a alguém que vais à casa de banho largar um braço. Ou que acabaste de ir à casa de banho largar um braço.",
  "Diz a alguém que se há coisa de que te orgulhas é da educação que recebeste em casa.",
  "Comenta a personalidade de alguém dizendo que essa pessoa “É de luas.”",
  "Faz uma aposta com alguém em relação à quantidade de bebida. Se vai sobrar ou se vai faltar. Se um de vocês achar que vai faltar, comuniquem ao Rafa, Pedro ou Chico.",
  "Diz que tens ido à Web Summit todos os anos e adoras o ambiente, dizendo que para além de ser um evento interessante, é muito bom para fazer networking.",
  "Incentiva uma pessoa a beber o resto da noite com uma palhinha. Diz-lhe que assim o álcool bate mais. Pergunta-lhe se ela sabia. Se ela souber, oferece-lhe o maior sorriso que tiveres.",
  "Tentem adivinhar qual vai ser o nome atribuído à próxima tempestade.",
  "Faz uma transferência de",
  "1 cêntimo para uma pessoa que esteja na festa. Se a pessoa te vier perguntar o que se passou, diz que é uma vibe que tens estado a cultivar nos últimos tempos.",
  "Faz uma transferência de",
  "1 cêntimo para uma pessoa que esteja na festa. Se a pessoa te vier perguntar o que se passou, diz que é uma vibe que tens estado a cultivar nos últimos tempos.",
  "Dá os parabéns a alguém, mesmo que a pessoa não faça anos e tu saibas disso perfeitamente.",
  "És uma pessoa muito brincalhona, lembra-te disso.",
  "Promete a alguém que não morres sem fazer uma viagem à Mongólia.",
  "Promete a alguém que não morres sem fazer uma viagem à Mongólia.",
  "Revela a alguém que ainda hás-de ser chefe de agrupamento de um grupo de escuteiros. Se a pessoa te desacreditar, diz que tens a estratégia toda pensada para chegar lá dentro de 5 anos e não digas mais nada.",
  "Aproveita o facto de a festa se chamar Festa do Escorpião, escolhe um signo qualquer e diz que as pessoas desse signo não são flor que se cheire.",
  "Vai ao pé da fogueira, pede licença para teres mais espaço de forma gestual e continua a inventar gestos como se quisesses dizer mais alguma coisa e a pessoa não estivesse a perceber.",
  "Revela a alguém que ainda hás-de ser chefe de agrupamento de um grupo de escuteiros. Se a pessoa te desacreditar, diz que tens a estratégia toda pensada para chegar lá dentro de 5 anos e não digas mais nada.",
  "Manda uma posta de pescada em relação ao número de pessoas que está na festa, dando a entender que tens um dom para esse tipo de aposta.",
  "Em conversa com uma ou mais pessoas, defende que o Bankinter é o melhor banco a operar em Portugal. Se te perguntarem porquê, responde “Epá porque é” e faz com que a conversa termine aí.",
  "Tenta envolver o maior grupo de pessoas para a discussão deste tema. Começa por dizer que as bolachas Maria continuam a ser a melhor bolacha do mercado e que podem vir os Filipinos, as Oreos e a puta que as pariu que nenhuma delas há-de ser melhor que a Maria. A asneira é importante, mas podes não usar.",
  "Convida alguém para ir subir a oliveira contigo. Diz que tens saudades de subir a uma árvore e que só em cima de uma árvore te sentes verdadeiramente rela- cionado com a Mãe Natureza. “Mãe Natureza” é uma expressão imprescindível neste diálogo.",
  "Diz a alguém que estás a pensar contratar um mordomo para tua casa. Que estás numa nova fase da tua vida e que há coisas de que já não podes prescindir.",
  "Diz que se fosse para fazer tatuagens que fosse de uma máquina retroescavadora nas costas, o logo das Jornadas Mundiais da Juventude no peito ou outra coisa bizarra à tua escolha.",
  "Pede a alguém que elabore sobre o conflito israelo-árabe. Quando a pessoa disser tudo o que conseguiu, fica em silêncio e dá-lhe um beijinho onde achares que te é permitido. Se for preciso, pede licença.",
  "Propõe um brinde ao Casamento Real. Leva a coisa a sério e continua o teu número com elogios ao vestido da noiva e ao porte do noivo.",
  "Ouve com atenção o que alguém esteja a dizer e quando ela terminar diz “Ya” de um modo que toda a gente ache estranho.",
  "Alimenta a teoria de que os organizadores da festa são drógádos.",
  "Faz com que alguém note que estás a bochechar com cerveja. Responde à pessoa, se ela se mostrar inquieta, que foi uma recomendação do teu dentista e para ela se meter na vida dela que tu não precisas que tomem conta de ti.",
  "Numa conversa sobre geografia, viagens ou outro tema qualquer, dá a entender que achas que a Hungria faz fronteira com Inglaterra.",
  "Tens de conseguir que a pessoa te prove que não faz com recurso ao google maps, já meio irritada contigo eventualmente, mas tens de aguentar. A vida é assim.",
  "Trata alguém por “chaval”. Se a pessoa ignorar, volta a tratá-la por “chaval”.",
  "Pergunta a que horas é que toca a Mopedbart? Se já tiver tocado, pergunta se podem meter outra vez. Envolve o Rafa neste assunto.",
  "Começa uma discussão sobre jardinagem. Fala das ferramentas, das plantas, de máquinas de cortar relva e relaciona este hobbie com o tema da saúde mental. Podes dizer que desde que tens perdido mais tempo a jardinar já não sentes um impulso de mandar pedras à bófia. Faz com que a pessoa se surpreenda com esta revelação e demonstre preocupação contigo. No final, tranquiliza-a.",
  "Mostra receio em relação à descida de temperatura e pede que te ajudem a superar essa ansiedade. Diz que a melhor forma de o fazerem é darem-te um abraço. Se conseguires mostra a carta.",
  "Fala sobre o Kamasutra e diz que sentes tens uma posição a acrescentar. Elabora de acordo com o que essa cabecinha andar aí a pensar, partilha com pessoas e avalia as reacções.",
  "Interrompe uma conversa para perguntar se alguém quer ir fazer uma formação em Excel. Diz que já te inscreveste e que tem estado a ser “absolutamente espectacular.”",
  "Pede uma sugestão de corte de cabelo a alguém e prende a pessoa a esse assunto durante o máximo de tempo que conseguires.",
  "Interrompe uma conversa para perguntar se alguém quer começar a ter aulas de italiano.",
  "Fala sobre o Kamasutra e diz que sentes tens uma posição a acrescentar. Elabora de acordo com o que essa cabecinha andar aí a pensar, partilha com pessoas e avalia as reacções.",
  "Fala sobre uma terra em Portugal onde nunca tenhas estado até que a pessoa se aperceba que estás a mentir.",
  "Interrompe uma conversa para perguntar se alguém quer ir fazer um curso de carpintaria.",
  "Interrompe uma conversa para perguntar se alguém quer ir fazer uma formação em Excel. Diz que já te inscreveste e que tem estado a ser “absolutamente espectacular.”",
  "Convida alguém a ir contigo a algum lado e anda os primeiros metros como se estivesses a jogar à macada. O objectivo é que a pessoa que vai ao teu lado fique - WTF????",
  "Chega à pista de dança com as duas mãos na cintura e depois começa a dançar.",
  "Chega à pista de dança com as duas mãos na cintura e depois começa a dançar.",
  "Chega à pista de dança com as duas mãos na cintura e depois começa a dançar.",
  "Diz que estás a pensar começar a roer as unhas e nada nem ninguém te poderão demover.",
  "Diz que estás a pensar começar a roer as unhas.",
  "Numa discussão sobre sopas, diz que a base de uma boa sopa é amendoim e deixa este conselho no ar como se já andasses nisto há muitos anos.",
  "Numa discussão sobre sopas, diz que a base de uma boa sopa é amendoim e deixa este conselho no ar como se já andasses nisto há muitos anos.",
  "Interpela alguém para lhe dizer que estás muito impressionado(a). Se ela perguntar com quê, não digas nada.",
  "Interpela alguém para lhe dizer que estás muito impressionado(a). Se ela perguntar com quê, não digas nada.",
  "Aproxima-te de um grupo de pessoas com que tenhas confiança e começa a ouvir a conversa. Quando alguém reparar, diz que é um exercício do estágio que estás a fazer nos Serviços Secretos e pede para te deixarem trabalhar.",
  "Recorda que as pessoas não percepcionam as cores da mesma maneira e que isso é um excelente ponto de partida para nos respeitarmos uns aos outros.",
  "Convida alguém a escolher um dia para irem fazer mergulho. Diz que tens uma enorme curiosidade em relação ao fundo do mar e que queres ver peixinhos.",
  "Recorda que as pessoas não percepcionam as cores da mesma maneira e que isso é um excelente ponto de partida para nos respeitarmos uns aos outros.",
  "Recorda que as pessoas não percepcionam as cores da mesma maneira e que isso é um excelente ponto de partida para nos respeitarmos uns aos outros.",
  "Recorda que as pessoas não percepcionam as cores da mesma maneira e que isso é um excelente ponto de partida para nos respeitarmos uns aos outros.",
  "Convida alguém para olhar para a Lua e elabora sobre a distância até à Lua, o papel Dela e nos pensamentos que Ela te suscita. Leva esta carta.",
  "Convida alguém para olhar para a Lua e elabora sobre a distância até à Lua, o papel Dela e nos pensamentos que Ela te suscita. Leva esta carta.",
  "Convida alguém a escolher um dia para irem fazer mergulho. Diz que tens uma enorme curiosidade em relação ao fundo do mar e que queres ver peixinhos.",
  "Convida alguém para olhar para a Lua e elabora sobre a distância até à Lua, o papel Dela e nos pensamentos que Ela te suscita. Leva esta carta.",
  "Canta a alguém uma parte do refrão da música “Uma melodia” do Valter Lobo.",
  "Dá uma pequena aula sobre colocação de voz, como se percebesses alguma coisa do assunto.",
  "Dá uma pequena aula sobre colocação de voz, como se percebesses alguma coisa do assunto.",
  "Dá uma pequena aula sobre colocação de voz, como se percebesses alguma coisa do assunto.",
  "Pergunta a alguém se acha normal já não veres uma borboleta há mais de dois anos.",
  "Pergunta a alguém se acha normal já não veres uma borboleta há mais de dois anos.",
  "Pergunta a alguém se acha normal já não veres uma borboleta há mais de dois anos.",
  "Mesmo que não seja esse o assunto, diz que vais mudar para a MEO e que te cansaste da Vodafone. Faz com que alguém se mostre surpreendido com a tua falta de timing.",
  "Convida alguém a ir à zona de terra batida perto do Moinho e começa a desenhar a palavra “AMOR” no chão. Mantém-te em silêncio durante todo",
  "o momento.",
  "Pensa durante algum tempo em frente a uma pessoa e depois apresenta-lhe, como se fosse uma conclusão, que o que interessa é que o pessoal é jovem e a malta curte.",
  "Pergunta de que cor são as penas do verdegaio? Se a pessoa não souber diz que são verdes e amarelas. Repete a pergunta mais algumas vezes durante a noite.",
  "Aproxima-te da fogueira e desenha um coração no chão. Podes desenhar mais, é como preferires.",
  "Aproxima-te da fogueira e desenha um coração no chão. Podes desenhar mais, é como preferires.",
  "Aproxima-te da fogueira e desenha um coração no chão. Podes desenhar mais, é como preferires.",
  "Pensa durante algum tempo em frente a uma pessoa e depois apresenta-lhe, como se fosse uma conclusão, que o que interessa é que o pessoal é jovem e a malta curte.",
  "Pergunta de que cor são as penas do verdegaio? Se a pessoa não souber diz que são verdes e amarelas. Repete a pergunta mais algumas vezes durante a noite.",
  "Pensa durante algum tempo em frente a uma pessoa e depois apresenta-lhe, como se fosse uma conclusão, que o que interessa é que o pessoal é jovem e a malta curte.",
  "Pergunta de que cor são as penas do verdegaio? Se a pessoa não souber diz que são verdes e amarelas. Repete a pergunta mais algumas vezes durante a noite.",
  "Pergunta de que cor são as penas do verdegaio? Se a pessoa não souber diz que são verdes e amarelas. Repete a pergunta mais algumas vezes durante a noite.",
  "Pergunta ao Chico se ele sabe de que cor são as penas do Verdegaio.",
  "Pergunta ao Chico se ele sabe de que cor são as penas do Verdegaio.",
  "Diz a alguém que queres ter um andaime dentro de casa e que sentes que será uma das próximas tendências da decoração de interiores.",
  "Sem que alguém o pudesse prever, começa a falar em italiano. Ou com sotaque, pelo menos. Podes dizer todas as palavras que souberes. Algumas ideias: “parmigiano regiano”, “grana padano”, “va fancu- lo”, “buona sera a tuti”, “va bene?”, “ferrari”, “milano”, “pasta”, “frances- co totti”, “manzana” e “la piu bela”",
  "Convida alguém para comentar a festa e diz que se tivesses sido tu a organizar, a festa tinha mais sal e a esta hora já estava tudo nu.",
  "Diz a alguém que queres ter um andaime dentro de casa e que sentes que será uma das próximas tendências da decoração de interiores.",
  "Sem que alguém o pudesse prever, começa a falar em italiano. Ou com sotaque, pelo menos. Podes dizer todas as palavras que souberes. Algumas ideias: “parmigiano regiano”, “grana padano”, “va fancu- lo”, “buona sera a tuti”, “va bene?”, “ferrari”, “milano”, “pasta”, “frances- co totti”, “manzana” e “la piu bela”",
  "Convida alguém para comentar a festa e diz que se tivesses sido tu a organizar, a festa tinha mais sal e a esta hora já estava tudo nu.",
  "Fala com alguém sobre rotinas de pequeno almoço e diz que tens optado por umas lascas de parmigianno regiano numa caminha de tomate quente com manjericão.",
  "Acusa alguém de ser antivax e pede-lhe uma justificação. Insiste que consideras isso uma posição irresponsável e dá espaço para a pessoa se defender ou assumir. No fim, mostra a carta e convida-a para um brinde.",
  "Convida alguém para comentar a festa e diz que se tivesses sido tu a organizar, a festa tinha mais sal e a esta hora já estava tudo nu.",
  "Numa conversa sobre ganhar",
  "algum dinheiro extra, diz que estás a pensar abrir uma sucata. Do que tens observado, é o negócio que está a render mais e que já desmontaste um Fiat Punto para vender às peças.",
  "Inventa um boato sobre a Cristina Ferreira. Tem de envolver “Alvaiázere”, “trens de cozinha”, “raspadinhas de um euro” e “caridade”.",
  "Convida alguém para comentar a festa e diz que se tivesses sido tu a organizar, a festa tinha mais sal e a esta hora já estava tudo nu.",
  "Pergunta a alguém se vai dormir a Fátima.",
  "Pergunta a alguém se vai dormir a Fátima.",
  "Numa conversa qualquer, dirige-te à última pessoa que falou dizendo que até um chimpanzé organizava melhor um raciocínio. Se a pessoa se ofender, mostra a carta.",
  "Numa conversa sobre ganhar",
  "algum dinheiro extra, diz que estás a pensar abrir uma sucata. Do que tens observado, é o negócio que está a render mais e que já desmontaste um Fiat Punto para vender às peças.",
  "Durante alguns segundos, imita a voz do Rodrigo Guedes de Carvalho ou a da Júlia Pinheiro.",
  "Diz que um dia destes te puseste a ver o Big Brother e que nunca te tinhas divertido tanto. Se a pessoa ficar surpreendida, insiste que ela tem de ver como as pessoas fazem com Game of Thrones.",
  "Começa uma conversa",
  "à volta da frase: “Masturbas-me com o coração e depois não queres que me venha com sentimentos.”",
  "Gaba-te de teres tido 5 a EVT. Demora o tempo que for preciso até alguém mostrar desagrado com a tua bazófia.",
  "Sugere a alguém que ficava melhor se rapasse o cabelo.",
  "Começa uma conversa",
  "à volta da frase: “Masturbas-me com o coração e depois não queres que me venha com sentimentos.”",
  "Começa uma conversa",
  "à volta da frase: “Masturbas-me com o coração e depois não queres que me venha com sentimentos.”",
  "Revela que ouviste dizer que a EMEL vai começar a operar em Alcobaça, Batalha, Marinha Grande, Leiria, Porto de Mós e Peniche.",
  "Revela que ouviste dizer que a EMEL vai começar a operar em Alcobaça, Batalha, Marinha Grande, Leiria, Porto de Mós e Peniche.",
  "Pergunta a alguém se sabe andar a cavalo. Independentemente do que a pessoa responda, diz que não é “andar a cavalo”, é MONTAR. Sobe o tom de voz nesta segunda fala.",
  "Diz que se fosses tu a mandar andava tudo de barbatanas.",
  "Diz que se fosses tu a mandar andava tudo de barbatanas.",
  "Explica a alguém que a melhor forma de comer caldo verde é com um garfo. Não desistas de convencer a pessoa.",
  "Pergunta a alguém se sabe andar a cavalo. Independentemente do que a pessoa responda, diz que não é “andar a cavalo”, é MONTAR. Sobe o tom de voz nesta segunda fala.",
  "Comenta com alguém o teu desconforto com a roupa que trouxeste e diz que a nível de calçado estavas bem era com um chinelinho de enfiar no dedo.",
  "Comenta com alguém o teu desconforto com a roupa que trouxeste e diz que a nível de calçado estavas bem era com um chinelinho de enfiar no dedo.",
  "Dá a tua opinião sobre o que mudavas no rugby e diz que deviam trocar aquela bola por uma tostadeira industrial e que os jogadores têm porte suficiente para jogarem com um objecto mais pesado.",
  "Numa conversa sobre animais, diz que o mundo seria um lugar mais agradável se os cães e os gatos domésticos fossem substituídos por esquilos",
  "e doninhas.",
  "Comenta com alguém que estás com demasiados seguidores no Instagram e que vais entregar a gestão da tua conta a uma agência.",
  "Dá a tua opinião sobre o que mudavas no rugby e diz que deviam trocar aquela bola por uma tostadeira industrial e que os jogadores têm porte suficiente para jogarem com um objecto mais pesado.",
  "Revela que andas à espera da tua oportunidade para misturar whiskas saquetas num frasco de cereais de um serviço de pequeno almoço de hotel.",
  "Do nada, pede aos teus amigos(as) que tenham mais respeito pela tua condição física.",
  "Compara alguém a um pinguim.",
  "Revela que andas à espera da tua oportunidade para misturar whiskas saquetas num frasco de cereais de um serviço de pequeno almoço de hotel.",
  "Diz que o que faz falta em Porto de Mós é um bom Centro de Congressos.",
  "Comenta com alguém que estás com demasiados seguidores no Instagram e que vais entregar a gestão da tua conta a uma agência.",
  "Dirige-te a alguém com o tom condescendente com que algumas pessoas falam com crianças e idosos. Permite que a pessoa se exalte com a tua postura e abraça-a para pedir desculpa.",
  "Revela preocupação com a dívida pública americana.",
  "Defende que o gmail é pior que o Hotmail e oferece menos garantias de segurança.",
  "Arranja maneira de falar sobre os estádios de futebol e diz que estiveste envolvido no desenho do Estádio do Braga.",
  "Pergunta se a capela tem wi-fi.",
  "Diz a alguém que desde há dois ou três meses para cá só comes iogurtes que estejam há dois meses fora do prazo.",
  "Pede para te recordarem se os",
  "ovos estão estragados quando flutuam ou se isso significa que estão bons. Agradece o esclarecimento com dois beijinhos e um abraço demorado.",
  "Sugere que o Haka foi inventado",
  "no Alto Minho e que a equipa da Nova Zelândia devia ter vergonha dessa apropriação. Passado algum tempo, diz que vais avançar para Tribunal e pede apoio para essa iniciativa.",
  "Com entusiasmo, comenta uma descoberta recente que indica que há atividade vulcânica na Serra de Aire e Candeeiros.",
  "Pede para uma pessoa verificar se tens bolor nos bolsos de trás das calças.",
  "Do nada, agradece a alguém a preocupação contigo, que valorizas muito essa atenção mas acaba a pedir para ela não invadir a tua bolha.",
  "Como se tivesses acabado de ouvir esse boato, pergunta se é verdade que os organizadores tentaram convidar o",
  "Rui Reininho para fazer uma presença na festa.",
  "Diz que descobriste que o rapaz que aparecia na caixa dos Kinder ainda é da tua família.",
  "Pede a alguém que te explique qualquer coisa, mas que tenha o cuidado de te fazer um desenho.",
  "Anuncia algumas das tuas principais ideias para a reforma: atravessar passadeiras com um carrinho de mão, escrever frases de amor em cabines telefónicas e bater palmas todos os dias ao meio-dia em ponto.",
  "Como se tivesses acabado de ouvir esse boato, pergunta se é verdade que os organizadores tentaram convidar o",
  "Rui Reininho para fazer uma presença na festa.",
  "Diz ao pessoal que está na fogueira que há castanhas, mas que estão escondidas e é preciso jogar ao “Quente – Frio” para as encontrar. Pergunta quem está disponível para jogar e falem com um dos organizadores.",
  "Calcula a margem de lucro que o Mama a Bucha deve fazer por cada pita shoarma.",
  "Pede ajuda a várias pessoas para este exercício.",
  "Diz que sentiste falta de bróculos ao jantar.",
  "Anuncia que vais sortear um alvo para fazeres um ataque informático.",
  "Partilha com uma pessoa que numa chamada Zoom, não houve uma única em que tivesses as calças vestidas. Se a conversa se alongar, diz que estás à espera de bater o record mundial, actualmente detido por um informático sueco na casa dos 43 anos e que conta com 567 vídeo-chamadas sem calças.",
  "Sugere a alguém que faça uma massagem com argila. Inventa um benefício qualquer da argila.",
  "Pergunta a alguém se tem o número da Sic Notícias e diz que vais ligar para um programa de opinião a alertar para o perigo de extinção do saramugo.",
  "É um peixe.",
  "Diz que demorou algum tempo até mudares a tua perspectiva sobre flores e que hoje em dia uma das melhores formas de alegrarem o teu dia é enviarem-te um raminho de salsa.",
  "Defende que Carmex é o melhor baton do mercado. Aproveita para fazer uma rima com o nome, por exemplo: Eu e o meu Carmex viemos à festa dar flex.",
  "Tenta surpreender alguém dizendo que o Eiffel é que projectou grande parte da urbanização da Nova Leiria.",
  "De forma apreensiva e com alguma consternação, diz que sabes de fonte segura que este é o último ano em que há Pão-por-Deus porque o nome foi patenteado por uma paroquia no País Basco.",
  "Numa única tirada sobre o teu destino profissional, diz da forma mais decidida que conseguires que queres ser guia nas Grutas de Santo António.",
  "Pergunta a alguém se já se sabe mais alguma coisa sobre o ataque informático que fizeram à Papelaria Rossio.",
  "Propõe a alguém que cante o alfabeto em inglês. Diz que estás aborrecido(a) e que precisas dessa musicalidade. Começa tu com “ei bi si” e depois pede à pessoa para continuar enquanto ficas apenas a ouvir. Boa sorte.",
  "Finge que não ouviste bem o que te disseram e pede para repetir o maior número de vezes que conseguires, que é até a outra pessoa se fartar. Cuidado que há malta que tem pavio curto.",
  "Convida a alguém a ir contigo a ir ver uma coisa contigo à cozinha. Quando lá chegares, diz que te esqueceste do que lhe querias mostrar.",
  "Arranja forma de saber os planos das pessoas para este Domingo, será a forma de dizeres que para ti o Domingo é um dia sagrado para dormir, comer e descansar. Dá a entender que condenas qualquer plano que saía deste perímetro, a menos que seja para ir andar de baloiço.",
  "Revela em público que o Marques Mendes é teu padrinho de baptismo.",
  "Pergunta a alguém se pode ir contigo buscar bananas.",
  "Sê teatral e dirige-te a alguém como se estivesses muito nervoso.",
  "Dá um abraço a alguém durante 20 segundos.",
  "Tens decronometrar e mostrar-lhe no fim.",
  "Dá um abraço a alguém durante 20 segundos.",
  "Tens decronometrar e mostrar-lhe no fim.",
  "Pergunta a alguém se viu uma estrela cadente. Faz o teatro todo à volta desse tipo de acontecimento e pergunta se a pessoa quer procurar uma segunda. Ao fim de alguns segundos/minutos, diz que só querias estar com ela um bocadinho em silêncio. Estive para escrever “No final beijem-se”, mas reconsiderei.",
  "Aproxima-te da porta do salão e faz de segurança durante algum tempo. Pergunta às pessoas que estiverem a entrar se sabem que o pessoal é jovem e a malta curte.",
  "Insurge-te contra as calculadoras e diz que são as grandes responsáveis pela perda de capacidade humana para resolver problemas de matemática. Desenvolve a partir daqui, passando pela perda de capacidade de raciocínio, preguiça, etc. E que noutro dia precisas te de ir buscar pauzinhos para saber quanto eram 5 + 8.",
  "Numa conversa sobre trabalho, diz que reconfiguraste o computador e meteste Comic Sans como tipo de letra porque torna o teu ambiente de trabalho mais divertido.",
  "Pergunta a alguém se viu uma estrela cadente. Faz o teatro todo à volta desse tipo de acontecimento e pergunta se a pessoa quer procurar uma segunda. Ao fim de alguns segundos/minutos, diz que só querias estar com ela um bocadinho em silêncio.",
  "Aproxima-te da porta do salão e faz de segurança durante algum tempo. Pergunta às pessoas que estiverem a entrar se sabem que o pessoal é jovem e a malta curte.",
  "Pergunta se alguém sabe de onde vêm as bolotas. Se a pessoa responder que é de uma árvore, diz que a tua vem do Bairro Alto LOL",
  "Pergunta a alguém se viu uma estrela cadente. Faz o teatro todo à volta desse tipo de acontecimento e pergunta se a pessoa quer procurar uma segunda. Ao fim de alguns segundos/minutos, diz que só querias estar com ela um bocadinho em silêncio.",
  "Pergunta a alguém se viu uma estrela cadente. Faz o teatro todo à volta desse tipo de acontecimento e pergunta se a pessoa quer procurar uma segunda. Ao fim de alguns segundos/minutos, diz que só querias estar com ela um bocadinho em silêncio.",
  "Pergunta a alguém se viu uma estrela cadente. Faz o teatro todo à volta desse tipo de acontecimento e pergunta se a pessoa quer procurar uma segunda. Ao fim de alguns segundos/minutos, diz que só querias estar com ela um bocadinho em silêncio.",
  "Aproxima-te da porta do salão e faz de segurança durante algum tempo. Pergunta às pessoas que estiverem a entrar se sabem que o pessoal é jovem e a malta curte.",
  "Insurge-te contra as calculadoras e diz que são as grandes responsáveis pela perda de capacidade humana para resolver problemas de matemática. Desenvolve a partir daqui, passando pela perda de capacidade de raciocínio, preguiça, etc. E que noutro dia precisas te de ir buscar pauzinhos para saber quanto eram 5 + 8.",
  "Pergunta se alguém sabe de onde vêm as bolotas. Se a pessoa responder que é de uma árvore, diz que a tua vem do Bairro Alto LOL",
  "Sexo",
  "Pergunta se alguém sabe de onde vêm as bolotas. Se a pessoa responder que é de uma árvore, diz que a tua vem do Bairro Alto LOL",
  "Sexo",
  "Envolve o maior número de pessoas que conseguires para tentarem descobrir as razões de não haver pombos em Porto de Mós.",
  "Envolve o maior número de pessoas que conseguires para tentarem descobrir as razões de não haver pombos em Porto de Mós.",
  "Leva alguém a acreditar que apagaste todas as tuas redes sociais. Ou que vais apagar amanhã, se achares a primeira opção muito difícil.",
  "Leva alguém a acreditar que apagaste todas as tuas redes sociais. Ou que vais apagar amanhã, se achares a primeira opção muito difícil.",
  "Diz que se pudesses adoptar um animal, neste momento adoptavas um flamingo.",
  "Fala sobre a praga de javalis.",
  "Propõe a alguém que vá assistir a uma catequese e diz que achas que só lhe fazia bem.",
  "Trata alguém por Zbriguels.",
  "Promove um abraço de grupo entre os organizadores.",
  "Pede aos organizadores que se cumprimentem com dois beijinhos.",
  "Diz que o Almada Negreiros era motorista do Fernando Pessoa.",
  "Pede a alguém que te recorde como é que se faz uma tosta mista.",
  "Droga",
  "Pede a alguém que verifique se tens os dentes limpos. Pede-lhe que jure pelo que lhe é mais sagrado que te está a dizer a verdade e podes agarrar-lhe a mão em tom de súplica.",
  "Marcha em direcção à casa de banho.",
  "Demonstra um entusiasmo exagerado em relação ao record mundial batido pela Rosa Mota.",
  "Finge que estás a jogar às escondidas, para as pessoas ficarem com a sensação de que se está a jogar esse jogo na Festa e terem o instinto de se esconderem também.",
  "Revela que foste contactado para te juntares à Anonymus mas que recusaste o convite porque não permitiam teletrabalho.",
  "Revela que foste contactado para te juntares à Anonymus mas que recusaste o convite porque não permitiam teletrabalho.",
  "Finge que perdeste as chaves do carro e pede ajuda. Quantas mais pessoas envolveres...não acontece nada, pode ser só giro.",
  "Pede para alguém te coçar as costas e sê o mais exigente possível.",
  "Pede a alguém que dê uma ordem de preferência aos frutos de verão.",
  "Diz que o Natal está aí à porta e que o tempo passa mesmo a correr. Não desistas até a pessoa dizer que também concorda. Continua a conversa sobre o Natal e diz-lhe que ainda fazes lista para o Pai Natal, mas que gostavas que isso ficasse só entre vocês.",
  "Benze-te antes de entrares ou saíres do salão como se fosses um jogador de futebol.",
  "Conta a alguém que a semana passada sonhaste que eras uma beterraba e que o sonho acabou quando te enfiaram dentro de uma panela de sopa.",
  "Dá a entender que consomes estupefacientes antes de fazeres exercício físico.",
  "Pergunta a alguém se sabe quanto custa mandar fazer um portão de correr. Elabora um pouco mais sobre a tua ideia de formato do portão e pede sugestões para a cor com que o deverás pintar.",
  "Disserta com alguma seriedade sobre o provérbio",
  "“É preciso uma aldeia inteira para criar um filho”.",
  "Podes adoptar um tom sério ou levar a conversa para a brincadeira.",
  "Revela que começaste uma colecção de cachimbos e que já tens 23.",
  "Numa conversa sobre o universo profissional, diz a alguém que mudaste de emprego, vais assumir call center na Endesa e que na segunda-feira entras em contacto com ela. Tenta começar já a convencer a pessoa a fazer contrato com a Endesa. Se ela disser que já tem, diz que precisas de provas e queres ver o contrato.",
  "Partilha com algumas pessoas que vais investir num Tesla",
  "e que sentes estar em condições de ser um agente da transição energética.",
  "Entrega um papelinho a alguém a dizer “Amo-te”",
  "Defende que o sol é uma construção social e não digas mais nada nem tentes fundamentar.",
  "Revela a alguém a primeira coisa que fazes de manhã: desejar bom dia nas redes sociais de celebridades. Dá alguns exemplos: Manuel Luís Goucha, Fanny, Rodrigo Guedes de Carvalho, Camané, Vitor Sobral e Margarida Rebelo Pinto.",
  "Lamenta o facto de já não se comerem ervilhas como antigamente e não respondas se alguém te perguntar porque estás a dizer isso.",
  "É um daqueles jogos para as pessoas fazerem coisas, se lhes apetecer.",
  "Se não estiveres capaz, está tudo bem, não há nenhuma obrigação de jogar, nenhum resultado a atingir e o único vencedor, a existir, é a Festa.",
  "Mas cuidado, não é por ser um escorpião com botas a segurar uma trompete e uma garrafa de vinho que deixa de ser um Escor- pião.",
  "Prudência.",
  "Tem em mente que se trata do signo mais misterioso e intenso do zodíaco.",
  "O melhor é deixá-lo relativamente isolado e não o provocar muito, a picada de nonsense é forte e pode representar alguns riscos.",
];
